### PR TITLE
New Home Page 

### PR DESCRIPTION
**Pull request by domchang1**
Side by side home page with two different dropdowns: Attendance and CHAC. Also added two different svgs and cleaned up everything

### CODE REVIEW

**Comment by AllusiveWheat** [comment]
Can I make a quick commit to add some simple dark mode support?

**Comment by domchang1** [comment]
> Can I make a quick commit to add some simple dark mode support?

Sure

**Review by AllusiveWheat — APPROVED** [review]
LGTM

**Review by SDBagel — APPROVED** [review]
There is an issue on larger screens where the homepage is not taking up the full width. I will merge anyway since we will be doing future style passes to tidy and optimize code, and it will be easier to resolve the issue then.

**Pull request merged**
